var Core=(function(router){this.router=router;var basepath=router.basepath;var clearpath=router.clearpath;this.pageContents=[];this.checkPageContent=function(pageUrl){for(var i=0;i<this.pageContents.length;i++){if(this.pageContents[i].url===pageUrl){return!0}}
    return!1};this.adjustLinks=function(){var links=document.getElementsByTagName("a");var imgs=document.getElementsByTagName("images");var regexText="(("+this.router.clearpath.replace(/\//g,"\\\/")+").*)|((http:\\/\\/).*)|((\\/\\/).*)";var regex=new RegExp(regexText);for(var i=0;i<links.length;i++){if(!regex.test(links[i].getAttribute("href"))){var url=links[i].getAttribute("href");url=this.adjustUrl(url);links[i].setAttribute("href",url);this.router.setLink(links[i])}}
    for(i=0;i<imgs.length;i++){if(!regex.test(imgs[i].getAttribute("src"))){var src=imgs[i].getAttribute("src");imgs[i].setAttribute("src",this.router.clearpath+"/"+src)}}};this.adjustUrl=function(url){var regexText="(("+this.router.clearpath.replace(/\//g,"\\\/")+").*)|((http:\\/\\/).*)|((\\/\\/).*)";var regex=new RegExp(regexText);if(!regex.test(url)){if(url==="/"){url=""}
    url=this.router.clearpath+"/"+url}
    return url};this.adjustRefs=function(){var styles=document.getElementsByTagName("link");var scripts=document.getElementsByTagName("script");var regexText="(("+this.router.clearpath.replace(/\//g,"\\\/")+").*)|((http:\\/\\/).*)|((\\/\\/).*)";var regex=new RegExp(regexText);for(var i=0;i<styles.length;i++){if(!regex.test(styles[i].getAttribute("href"))){var href=styles[i].getAttribute("href");styles[i].setAttribute("href",this.adjustUrl(href))}}
    for(i=0;i<scripts.length;i++){if(!regex.test(scripts[i].getAttribute("src"))){var parent=scripts[i].parentNode;var src=scripts[i].getAttribute("src");scripts[i].setAttribute("src",this.adjustUrl(src));var newScript=document.createElement("script");newScript.setAttribute("src",this.router.clearpath+"/"+src);newScript.setAttribute("tyle",scripts[i].getAttribute("type"));parent.replaceChild(newScript,scripts[i])}}};this.toAbsolutePath=function(base,relative){if(relative.charAt(0)==="/"){relative=relative.substring(1)}
    var stack=base.split("/");var parts=relative.split("/");stack.pop();for(var i=0;i<parts.length;i++){if(parts[i]===".")
        continue;if(parts[i]==="..")
        stack.pop();else stack.push(parts[i])}
    return stack.join("/")};this.importFile=function(file,callback){file=file.charAt(file.length-1)==="/"?file.substring(0,file.length-1):file;var core=this;if(this.checkPageContent(file)){var pageObject={};for(var i=0;i<this.pageContents.length;i++){if(file===this.pageContents[i].url){pageObject={response:this.pageContents[i].content,responseUrl:this.pageContents[i].url};break}}
    callback(pageObject)}else{var xhr=new XMLHttpRequest();xhr.open("GET",file,!0);xhr.send();var timer=setInterval(function(){if(xhr.response!==""){if(!core.checkPageContent(file)){core.pageContents.push({url:file,content:xhr.response})}
    callback(xhr);clearInterval(timer)}},20)}};this.importAndExec=function(routeData,getVars){var core=this;var routeContent=document.getElementById("route-content");var cssInsertedNow=!1;var fileFolder=router.basepath+"/src/app/pages/";routeData.setup=routeData.setup.charAt(0)!=="/"?routeData.setup:routeData.setup.substring(1);var filePath=fileFolder+routeData.setup+".page.js";getVars=(typeof getVars!=="undefined")?getVars:"";var pageScript=document.getElementById("page-script");if(pageScript!==null){routeContent.removeChild(pageScript)}
    window.page=null;var script=document.createElement("script");script.src=filePath;script.id="page-script";routeContent.appendChild(script);var interval=setInterval(function(){if(page!==null){var prevStyles=document.getElementsByClassName("dynamicStyle");for(i=0;i<prevStyles.length;i++){prevStyles[i].setAttribute('class','dynamicStyle old')}
        if(typeof page.title!=="undefined"){document.title=page.title}else{document.title=core.pageContents[0].title}
        if(routeData.setup.charAt(0)==="/"){routeData.setup=routeData.setup.substring(1)}
        var pathArray=routeData.setup.split("/");pathArray[pathArray.length-1]="";var htmlFolder=fileFolder+pathArray.join("/");if(typeof page.pageFile!=="undefined"){var htmlPath=core.toAbsolutePath(htmlFolder,page.pageFile);core.importFile(htmlPath,function(pageContent){if(pageContent.response!==""){if(pageContent.response!==core.pageContents[0].content){if(typeof page.styleFile!=="undefined"){var i1=setInterval(function(){var style=document.getElementsByClassName("dynamicStyle");if(style.length>0){routeContent.innerHTML=pageContent.response;clearInterval(i1)}},20)}else{routeContent.innerHTML=pageContent.response}}
            var regexLink=new RegExp(/<a.*>.*<\/a>/g);if(regexLink.test(pageContent.response)){var i3=setInterval(function(){var links=document.getElementsByTagName("a");if(links.length>0){core.adjustLinks();clearInterval(i3)}},20)}}})}
        if(typeof page.styleFile!=="undefined"){var cssPath=core.toAbsolutePath(htmlFolder,page.styleFile);core.importFile(cssPath,function(styleContent){if(styleContent.response!==core.pageContents[0].content&&!cssInsertedNow){var style=document.createElement("link");style.type="text/css";style.href=cssPath;style.rel="stylesheet";style.className="dynamicStyle";document.head.appendChild(style);cssInsertedNow=!0;prevStyles=document.getElementsByClassName("dynamicStyle old");for(i=0;i<prevStyles.length;i++){document.head.removeChild(prevStyles[i])}}})}else{for(i=0;i<prevStyles.length;i++){document.head.removeChild(prevStyles[i])}}
        if(typeof page.handler!=="undefined"){setTimeout(function(){if(typeof page.pageFile!=="undefined"){var i=1;var i2=setInterval(function(){if(routeContent!==""){page.handler(getVars);clearInterval(i2);i++}},20)}else{page.handler(getVars)}},20)}
        clearInterval(interval)}},20)}});var Router=(function(){this.core=new Core(this);this.getRootPath=function(){return location.protocol+"//"+location.host+"/"};this.getExtraPath=function(){var rootPath=this.getRootPath();var relativePath=document.location.pathname.substring(1);var extraPath=(rootPath+relativePath).substring(this.basepath.length);var firstChar=extraPath.substring(0,1);if(firstChar==="/"){extraPath=extraPath.substring(1)}
    return extraPath};this.getBasePath=function(){var appPath=document.getElementsByTagName("base")[0].href;var firstChar=appPath.substring(0,1);var lastChar=appPath.substring(appPath.length-1);if(firstChar==="/"){appPath=appPath.substring(1)}
    if(lastChar==="/"){appPath=appPath.substring(0,appPath.length-1)}
    return appPath};this.getClearRelativePath=function(){var relativeAppPath=document.getElementsByTagName("base")[0].getAttribute("href");var firstChar=relativeAppPath.substring(0,1);var lastChar=relativeAppPath.substring(relativeAppPath.length-1);if(firstChar!=="/"){relativeAppPath="/"+relativeAppPath.substring(1)}
    if(lastChar==="/"){relativeAppPath=relativeAppPath.substring(0,relativeAppPath.length-1)}
    return relativeAppPath};this.basepath=this.getBasePath();this.clearpath=this.getClearRelativePath();this.setLink=function(link){var router=this;var url=link.getAttribute("href");var target=link.getAttribute("target");var sameWindow=(target===null||target==="_self"||target==="self");link.onclick=function(e){if(sameWindow){e.preventDefault();if(link.getAttribute("onclick")!==null){var execCode=new Function(link.getAttribute("onclick"));execCode.apply(this)}
    var obj={Title:"",Url:url};history.pushState(obj,obj.Title,obj.Url);router.execute()}}};this.execute=function(){var path=this.getExtraPath();for(var i=0;i<routes.length;i++){if((path===""&&(routes[i].path===""||routes[i].path==="/"))||path===routes[i].path)
{this.core.importAndExec(routes[i]);return}
else{var clearRoute="";var clearUrl="";if(routes[i].path.charAt(routes[i].path.length-1)==="/"){clearRoute=routes[i].path.substring(0,routes[i].path.length-1)}else{clearRoute=routes[i].path}
    if(routes[i].path.charAt(0)==="/"){clearRoute=clearRoute.substring(1)}else{clearRoute=clearRoute}
    if(path.charAt(path.length-1)==="/"){clearUrl=path.substring(0,path.length-1)}else{clearUrl=path}
    if(path.charAt(0)==="/"){clearUrl=clearUrl.substring(1)}else{clearUrl=clearUrl}
    var splitRoute=clearRoute.split("/");var splitPath=clearUrl.split("/");if(splitPath.length===splitRoute.length){for(var j=0;j<splitPath.length;j++){if(splitPath[j]===splitRoute[j]||(/{.+}/g).test(splitRoute[j])){if(j===splitPath.length-1){var vars=[];for(var k=0;k<splitRoute.length;k++){if((/{.+}/g).test(splitRoute[k])){var param=(/({.+})/g).exec(splitRoute[k])[0];var varName=param.replace(/[{}]/g,"");vars.push({name:varName,content:splitPath[k]})}}
        var getVars={};for(k=0;k<vars.length;k++){getVars[vars[k].name]=vars[k].content}
        this.core.importAndExec(routes[i],getVars);return}}else{break}}}
    if(clearRoute.trim()==="*"){var core=this.core;var route=routes[i];this.core.importFile(path,function(pageContent){if(pageContent.response===core.pageContents[0].content){core.importAndExec(route)}
    else{window.location.replace(path)}});return}}}
    var router=this;var route=routes[i];this.core.importFile(path,function(pageContent){if(pageContent.response===router.core.pageContents[0].content){var prevStyles=document.getElementsByClassName("dynamicStyle");for(i=0;i<prevStyles.length;i++){document.head.removeChild(prevStyles[i])}
        var prevScript=document.getElementById("page-script");if(prevScript!==null){document.head.removeChild(prevSript)}
        var routeContent=document.getElementById("route-content");routeContent.innerHTML="<h1>Page not found </h1>";routeContent.innerHTML+="<h4>(HTTP 404)</h4>";var linkHome=document.createElement("a");var linkText=document.createTextNode("Go back to home");linkHome.setAttribute("href",router.basepath);linkHome.appendChild(linkText);routeContent.appendChild(linkHome);router.setLink(linkHome)}
    else{window.location.replace(path)}})}});var App=(function(){var started=!1;var router=new Router();var core=router.core;this.data=[];var start=function(){started=!0;var css=document.getElementsByClassName("mainCss");if(css.length===0){var appPath=router.clearpath;var mainCss=appPath+"/main.css";var link=document.createElement("link");link.type="text/css";link.rel="stylesheet";link.href=mainCss;link.className="mainCss";document.head.appendChild(link)}
    core.importFile('src/app/app.body.html',function(data){document.body.innerHTML=data.response;var routeScript=document.getElementById("route-list");if(routeScript===null){var script=document.createElement("script");script.src=router.basepath+"/src/app/app.routes.js";script.setAttribute("id","route-list");script.type="text/javascript";document.getElementById('route-content').appendChild(script)}
        var interval=setInterval(function(){if(typeof routes!=="undefined"){router.execute();core.adjustRefs();clearInterval(interval)}},10)})};this.ajax=function(ajaxObj){ajaxObj.method=(typeof ajaxObj.method!=="undefined")?ajaxObj.method:"GET";ajaxObj.async=(typeof ajaxObj.async!=="undefined")?ajaxObj.async:!0;ajaxObj.url=(typeof ajaxObj.url!=="undefined")?core.adjustUrl(ajaxObj.url):"";ajaxObj.success=(typeof ajaxObj.success!=="undefined")?ajaxObj.success:null;ajaxObj.fail=(typeof ajaxObj.fail!=="undefined")?ajaxObj.fail:null;var xhr=new XMLHttpRequest();xhr.open(ajaxObj.method,ajaxObj.url,ajaxObj.async);xhr.send();var timer=setInterval(function(){if(xhr.response!==""){if(xhr.status===200){if(ajaxObj.success!==null){ajaxObj.success(xhr)}}else{if(ajaxObj.fail!==null){ajaxObj.fail(xhr)}}
    clearInterval(timer)}},20)};this.redirect=function(url){if(url===""||url==="/"){url=router.basepath}
    var obj={Title:"",Url:url};history.pushState(obj,obj.Title,obj.Url);router.execute()};window.onpopstate=function(){return start()};return core.importFile(router.clearpath,function(data){if(data.response.trim()!==''&&!started){core.pageContents[0]={url:router.clearpath,content:data.response,title:document.title,name:"base"};start()}})});window.onload=function(){window.app=new App()}